# Generated by Django 3.2.8 on 2022-05-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IcreatV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_id', models.CharField(max_length=20, unique=True, verbose_name='CRIS등록번호')),
                ('scientific_title_kr', models.TextField(verbose_name='연구제목 국문')),
                ('scientific_title_en', models.TextField(verbose_name='연구제목 영문')),
                ('date_registration', models.DateTimeField(null=True, verbose_name='연구등록일')),
                ('date_updated', models.DateTimeField(null=True, verbose_name='최종갱신일')),
                ('date_enrolment', models.DateTimeField(null=True, verbose_name='첫 연구대상자 등록일')),
                ('type_enrolment_kr', models.CharField(blank=True, max_length=30, verbose_name='첫 연구대상자 등록여부 국문')),
                ('results_date_completed', models.DateTimeField(null=True, verbose_name='연구종료일')),
                ('results_type_date_completed_kr', models.CharField(blank=True, max_length=30, verbose_name='연구종료일/ 상태 국문')),
                ('study_type_kr', models.CharField(blank=True, max_length=40, verbose_name='연구종류 국문')),
                ('i_freetext_kr', models.TextField(blank=True, verbose_name='중재종류 국문')),
                ('phase_kr', models.CharField(blank=True, max_length=100, verbose_name='임상시험단계 국문')),
                ('source_name_kr', models.CharField(blank=True, max_length=200, verbose_name='연구비지원 기관명 국문')),
                ('primary_sponsor_kr', models.CharField(blank=True, max_length=200, verbose_name='연구책임 기관명 국문')),
                ('primary_outcome_1_kr', models.TextField(blank=True, verbose_name='주요결과변수 1 국문')),
            ],
            options={
                'db_table': 'icreat_v2',
            },
        ),
    ]
